- hosts: all
  become: yes
  tasks:
    - name: Debug ansible_host inside the role
      debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    - name: Create the receptor user
      user:
        name: "{{ receptor_user }}"
        shell: /bin/bash
    - import_role:
        name: ansible.receptor.podman
    - import_role:
        name: ansible.receptor.setup
