- name: Retrieve cluster info
  hosts: localhost
  gather_facts: no

  vars:
    aws_region: "ap-southeast-1"
    cluster_name: "sandbox-devops"

  tasks:
    - name: List files in /tmp
      shell: ls -l /tmp
      register: tmp_files

    - name: Show /tmp files
      debug:
        var: tmp_files.stdout_lines

    - name: Print the KUBECONFIG variable
      debug:
        var: lookup('env', 'KUBECONFIG')

    - name: Print all environment variables (optional)
      shell: printenv
      register: env_output

    - name: Display all environment variables
      debug:
        var: env_output.stdout_lines

    - name: Generate EKS authentication token
      command: aws eks get-token --cluster-name {{ cluster_name }} --region {{ aws_region }} --output json
      register: eks_token_json

    - name: Save EKS token to a variable
      set_fact:
        eks_token: "{{ (eks_token_json.stdout | from_json).status.token }}"

    # - name: Write kubeconfig to a file
    #   copy:
    #     content: "{{ kubeconfig_content }}"
    #     dest: "/tmp/kubeconfig"
    #     mode: 0600

    - name: Get pods in monitoring namespace
      kubernetes.core.k8s_info:
        # kubeconfig: "/tmp/kubeconfig"
        # api_key: "{{ EKS_TOKEN }}"
        api_key: "{{ eks_token }}"
        namespace: awx
        kind: Pod
      register: pods_info

    - name: Display pod information
      debug:
        var: pods_info.resources
