---
- name: Retrieve and Print Kubernetes Cluster Information
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get Kubernetes Cluster Info
      kubernetes.core.k8s_cluster_info:
      register: cluster_info

    - name: Print the Kubernetes Cluster Info
      debug:
        var: cluster_info
